source "https://rubygems.org/"

gem "middleman", "~>3"
gem "therubyracer"
gem "rb-inotify"
gem "bootstrap-sass"
gem "jquery-middleman"
gem "sass-rails"
gem "font-awesome-middleman"
gem "middleman-data_source"
